sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t anurag/docker-react -f Dockerfile.dev .

script:
  - docker run anurag/docker-react npm run test -- --coverage
